EJ2CoreEditors/EJ2CoreEditors/Controllers/Calendar/TimeZoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EJ2CoreEditors.Controllers.Calendar
{
    public partial class CalendarController : Controller
    {
        // GET: /<controller>/
        public IActionResult TimeZone()
        {
            var isoDate = "2013-06-13T14:00:00.000Z";
            ViewBag.value1 = "2013-06-13T14:00:00.000";
            ViewBag.value2 = isoDate;
            return View();
        }
    }
}

EJ2CoreEditors/EJ2CoreEditors/Controllers/DatePicker/PostBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EJ2CoreEditors.Controllers.DatePicker
{
    public class DatePickerPostBack
    {
        [Required(ErrorMessage = "Please enter the value")]
        public DateTime? value { get; set; }

    }
    public partial class DatePickerController : Controller
    {
        // GET: /<controller>/
        public IActionResult PostBack()
        {
            DatePickerPostBack val = new DatePickerPostBack();
            val.value = DateTime.Now;
            return View(val);
        }
        [HttpPost]
        public IActionResult PostBack(DatePickerPostBack model)
        {
            DatePickerPostBack val = new DatePickerPostBack();
            val.value = model.value;
            return View(val);
        }
    }
}

EJ2CoreEditors/EJ2CoreEditors/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EJ2CoreEditors.Models;

namespace EJ2CoreEditors.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EJ2CoreEditors/EJ2CoreEditors/Controllers/Sidebar/PartialViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EJ2CoreEditors.Controllers.Sidebar
{
    public partial class SidebarController : Controller
    {
        // GET: /<controller>/
        public IActionResult PartialView()
        {
            return PartialView("~/Views/Sidebar/PartialView.cshtml");
        }
    }
}

EJ2CoreEditors/EJ2CoreEditors/Controllers/TimePicker/PostBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EJ2CoreEditors.Controllers.TimePicker
{
    public class TimePickerPostBack
    {
        public DateTime? value { get; set; }
    }
    public partial class TimePickerController : Controller
    {
        // GET: /<controller>/
        public IActionResult PostBack()
        {
            var model = new TimePickerPostBack();
            model.value = DateTime.Now;
            return View(model);
        }
        [HttpPost]
        public IActionResult PostBack(TimePickerPostBack model)
        {
            return View(model);
        }
    }
}

EJ2CoreEditors/EJ2CoreEditors/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EJ2CoreEditors/EJ2CoreEditors/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EJ2CoreEditors/EJ2CoreEditors/Views/Home/Index.cshtml
<div class="sf-samples" style="margin-top:22px;">
    <ul class="ulstyle">
        <li class="list" style="list-style:none">
            <code> Calendar Samples </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="Calendar" asp-action="MinMaxProperties">Value, Min and Max properties</a>
                <hr />
                <a asp-area="" asp-controller="Calendar" asp-action="Globalization">Globalization</a>
                <hr />
                <a asp-area="" asp-controller="Calendar" asp-action="ModelBinding">Model Binding using code behind</a>
                <hr />
                <a asp-area="" asp-controller="Calendar" asp-action="PartialView">PartialView</a>
                <hr />
                <a asp-area="" asp-controller="Calendar" asp-action="TimeZone">Timezone sample</a>
                <hr />
            </div>
        </li>
        <li class="list" style="list-style:none">
            <code> DatePicker Samples </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="MinMaxProperties">Value, Min and Max properties</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="Globalization">Globalization</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="DatePickerFor">DatePickerFor</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="ModelBinding">Model Binding using code behind</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="PartialView">PartialView</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="AjaxCalling">DatePicker using Ajax</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="PostBack">Form PostBack</a>
                <hr />
                <a asp-area="" asp-controller="DatePicker" asp-action="TimeZone">Timezone sample</a>
                <hr />
            </div>
        </li>
        <li class="list" style="list-style:none">
            <code> DateTimePicker Samples </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="MinMaxProperties">Value, Min and Max properties</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="Globalization">Globalization</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="DateTimePickerFor">DateTimePickerFor</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="ModelBinding">Model Binding using code behind</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="PartialView">PartialView</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="AjaxCalling">DateTimePicker using Ajax</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="PostBack">Form PostBack</a>
                <hr />
                <a asp-area="" asp-controller="DateTimePicker" asp-action="TimeZone">Timezone sample</a>
                <hr />
            </div>
        </li>
        <li class="list" style="list-style:none">
            <code> DateRangePicker Samples </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="MinMaxProperties">Value, Min and Max properties</a>
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="Globalization">Globalization</a>
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="ModelBinding">Model Binding using code behind</a>
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="PartialView">PartialView</a>
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="AjaxCalling">DateRangePicker using Ajax</a>
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="PostBack">Form PostBack</a>
                <hr />
                <a asp-area="" asp-controller="DateRangePicker" asp-action="TimeZone">Timezone sample</a>
                <hr />
            </div>
        </li>
        <li class="list" style="list-style:none">
            <code> TimePicker Samples </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="MinMaxProperties">Value, Min and Max properties</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="Globalization">Globalization</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="TimePickerFor">TimePickerFor</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="ModelBinding">Model Binding using code behind</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="PartialView">PartialView</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="AjaxCalling">TimePicker using Ajax</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="PostBack">Form PostBack</a>
                <hr />
                <a asp-area="" asp-controller="TimePicker" asp-action="TimeZone">Timezone sample</a>
                <hr />
            </div>
        </li>
        <li class="list" style="list-style:none">
            <code> Sidebar Samples </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="Sidebar" asp-action="ModelBinding">Model Binding using code behind</a>
                <hr />
                <a asp-area="" asp-controller="Sidebar" asp-action="PartialView">PartialView</a>
                <hr />
            </div>
        </li>
        <li class="list" style="list-style:none">
            <code> SetCulture Sample </code>
            <div class="column">
                <hr />
                <a asp-area="" asp-controller="SetCulture" asp-action="SetCulture">SetCulture sample</a>
                <hr />
            </div>
        </li>
    </ul>
</div>